parameters:
#    api_rest.example.class: API\Bundle\RestBundle\Example

services:
#    api_rest.example:
#        class: %api_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
