API\Bundle\RestBundle\Entity\Item:
  properties:
    studyTitle:
      - NotBlank: ~
    host:
      - NotBlank: ~
    summary:
      - NotBlank: ~
    description:
      - NotBlank: ~
    accessType:
      - Choice: [public, limited, restricted]
    noOfViews:
      - Type:
          type: integer
    noOfAccessRequests:
      - Type:
          type: integer
    sampleSize:
      - Type:
          type: integer
    frequency:
      - Type:
          type: integer
    gender:
      - Choice: [male, female, other]

